apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-lq6p
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-lq6p
    app.kubernetes.io/part-of: tkrw-pr714-0075-0007-app
  name: devfile-sample-lq6p
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-lq6p
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-lq6p
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0007-tenant/tkrw-pr714-0075-0007-app/devfile-sample-lq6p@sha256:aa25adef4dc7f84a2efe581392352c1447ce0edb79f10f76bc61b6478817b2c3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
